import React, { useState } from 'react';
import { ArrowLeft, ArrowRight, ShieldAlert, CheckCircle } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

export default function Step2() {
  const navigate = useNavigate();
  const [invasive, setInvasive] = useState(null);
  const [active, setActive] = useState(null);
  const [duration, setDuration] = useState('');

  const calculateClass = () => {
    if (invasive === null || active === null || !duration) return null;
    
    // Simplified logic for MVP demonstration purposes
    if (invasive && duration === 'long-term') return { class: 'Class III', desc: 'Highest risk. Requires Notified Body audit for QMS and clinical data.', color: 'var(--danger)' };
    if (active && duration === 'short-term') return { class: 'Class IIb', desc: 'Medium-high risk. Requires Notified Body involvement.', color: 'var(--warning)' };
    if (!invasive && !active) return { class: 'Class I', desc: 'Low risk. Self-certification possible (unless measuring/sterile/reusable).', color: 'var(--success)' };
    
    return { class: 'Class IIa', desc: 'Medium risk. Requires Notified Body assessment.', color: 'var(--info)' };
  };

  const riskResult = calculateClass();

  return (
    <div className="animate-fade-in" style={{ paddingBottom: '4rem' }}>
      <button 
        className="btn btn-secondary mb-6" 
        onClick={() => navigate('/step-1')}
        style={{ marginBottom: '2rem' }}
      >
        <ArrowLeft size={16} /> Back to Step 1
      </button>

      <div className="glass-panel" style={{ padding: '2rem' }}>
        <div className="flex-between" style={{ marginBottom: '2rem' }}>
          <div>
            <h2 className="heading-lg mb-2">Step 2: Classify Your Device</h2>
            <p className="text-body">
              EU MDR divides devices into 4 risk classes based on vulnerability of the human body.
              Higher class = more evidence + stricter review + mandatory third-party audit.
            </p>
          </div>
          <ShieldAlert size={48} color="var(--primary)" opacity={0.5} />
        </div>

        <div className="grid-cols-2" style={{ marginBottom: '3rem' }}>
          {/* Question 1 */}
          <div className="glass-card">
            <h3 className="heading-md" style={{ marginBottom: '1rem' }}>1. Is it an invasive device?</h3>
            <p className="text-small" style={{ marginBottom: '1.5rem' }}>Penetrates inside the body, either through a body orifice or through the surface of the body.</p>
            <div style={{ display: 'flex', gap: '1rem' }}>
              <button 
                className={`btn ${invasive === true ? 'btn-primary' : 'btn-secondary'}`}
                onClick={() => setInvasive(true)}
              >
                Yes, it is invasive
              </button>
              <button 
                className={`btn ${invasive === false ? 'btn-primary' : 'btn-secondary'}`}
                onClick={() => setInvasive(false)}
              >
                No, non-invasive
              </button>
            </div>
          </div>

          {/* Question 2 */}
          <div className="glass-card">
            <h3 className="heading-md" style={{ marginBottom: '1rem' }}>2. Is it an active device?</h3>
            <p className="text-small" style={{ marginBottom: '1.5rem' }}>Depends on a source of energy other than that generated by the human body or gravity (e.g. software, electronics).</p>
            <div style={{ display: 'flex', gap: '1rem' }}>
              <button 
                className={`btn ${active === true ? 'btn-primary' : 'btn-secondary'}`}
                onClick={() => setActive(true)}
              >
                Yes, it is active
              </button>
              <button 
                className={`btn ${active === false ? 'btn-primary' : 'btn-secondary'}`}
                onClick={() => setActive(false)}
              >
                No, non-active
              </button>
            </div>
          </div>
          
          {/* Question 3 */}
          <div className="glass-card" style={{ gridColumn: '1 / -1' }}>
            <h3 className="heading-md" style={{ marginBottom: '1rem' }}>3. Duration of Use</h3>
            <div style={{ display: 'flex', gap: '1rem' }}>
              {['transient', 'short-term', 'long-term'].map(val => (
                <button 
                  key={val}
                  className={`btn ${duration === val ? 'btn-primary' : 'btn-secondary'}`}
                  onClick={() => setDuration(val)}
                  style={{ flex: 1, textTransform: 'capitalize' }}
                >
                  {val.replace('-', ' ')}
                  <div className="text-small" style={{ color: duration === val ? 'rgba(255,255,255,0.7)' : 'var(--text-muted)', display: 'block', marginTop: '0.25rem' }}>
                    {val === 'transient' && '< 60 mins'}
                    {val === 'short-term' && '≤ 30 days'}
                    {val === 'long-term' && '> 30 days'}
                  </div>
                </button>
              ))}
            </div>
          </div>
        </div>

        {riskResult && (
          <div className="result-card glass-card animate-fade-in" style={{ 
            background: 'var(--bg-surface-elevated)',
            borderColor: riskResult.color,
            boxShadow: `0 0 20px ${riskResult.color}20`,
            marginBottom: '2rem'
          }}>
            <div className="flex-between">
              <div>
                <p className="text-small text-muted" style={{ textTransform: 'uppercase', letterSpacing: '0.1em' }}>Estimated Classification</p>
                <h4 className="heading-xl" style={{ color: riskResult.color, margin: '0.5rem 0' }}>
                  {riskResult.class}
                </h4>
                <p className="text-body">{riskResult.desc}</p>
              </div>
              <div style={{ width: '80px', height: '80px', borderRadius: '50%', border: `4px solid ${riskResult.color}`, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                <CheckCircle size={40} color={riskResult.color} />
              </div>
            </div>
          </div>
        )}

        <div className="flex-between">
          <span className="text-small text-muted">
            Note: This is a simplified calculator. Refer to MDR Annex VIII for full rules.
          </span>
          <button 
            className="btn btn-primary" 
            disabled={!riskResult}
            onClick={() => navigate('/step-3')}
          >
            Continue to QMS <ArrowRight size={16} />
          </button>
        </div>
      </div>
    </div>
  );
}
